site_name: KToolBox
site_url: https://ktoolbox.readthedocs.io/
site_description: Documentation for KToolBox
repo_url: https://github.com/Ljzd-PRO/KToolBox
repo_name: Ljzd-PRO/KToolBox
copyright: Copyright © 2023 by Ljzd-PRO

watch:
- ktoolbox

nav:
  - Get Started:
    - Welcome to KToolBox: index.md
    - About Kemono: about-kemono.md
    - More: more.md
  - Configuration:
      - Guide: configuration/guide.md
      - Reference: configuration/reference.md
  - Commands: commands.md
  - iOS Shortcuts: shortcut.md
  - FAQ: faq.md
  - API Documentation: api.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English

        - locale: zh
          name: 中文（简体）

          nav_translations:
            Get Started: 开始
            Welcome to KToolBox: 欢迎使用 KToolBox
            About Kemono: 关于 Kemono
            More: 更多
            Configuration: 配置
            Guide: 向导
            Reference: 参考
            Commands: 命令
            iOS Shortcuts: iOS 快捷指令
            FAQ: 常见问题
            API Documentation: API 文档

          site_description: "KToolBox 文档"

          theme:
            palette:
              - media: "(prefers-color-scheme)"
                toggle:
                  icon: material/brightness-auto
                  name: 切换至自动
              - media: "(prefers-color-scheme: light)"
                scheme: default
                toggle:
                  icon: material/brightness-7
                  name: 切换至深色模式
              - media: "(prefers-color-scheme: dark)"
                scheme: slate
                toggle:
                  icon: material/brightness-4
                  name: 切换至浅色模式
          extra:
            analytics:
              provider: google
              property: G-LLM6CEJEH3
              feedback:
                title: 这个页面对你有帮助吗？
                ratings:
                  - icon: material/emoticon-happy-outline
                    name: 这个页面有帮助
                    data: 1
                    note: >-
                      感谢你的反馈！
                  - icon: material/emoticon-sad-outline
                    name: 这个页面可以改进
                    data: 0
                    note: >-
                      感谢你的反馈，你可以前往我们 GitHub 仓库 Issues 或 Discussion 页面提交更多建议！
  - tags
  - search

theme:
  name: material
  features:
    - search.suggest
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.top
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-LLM6CEJEH3
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! You can submit more advice on Issues or Discussion page of our GitHub Repository.

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde