name: Package using PyInstaller
description: Bundles a Python application and all its dependencies into a single package.

inputs:
  spec-path:
    description: Path of Spec file
    required: false
    default: "ktoolbox.spec"

  dist-path:
    description: Path of Spec file
    required: false
    default: "dist"

runs:
  using: "composite"
  steps:
    - name: Create Executable
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          poetry run pyinstaller ${{ inputs.spec-path }} --distpath ${{ inputs.dist-path }} --target-arch universal2
        else
          poetry run pyinstaller ${{ inputs.spec-path }} --distpath ${{ inputs.dist-path }}
        fi
      shell: bash

    - name: Copy Extra Files
      run: cp README.md README_zh-CN.md example.env .env LICENSE dist
      shell: bash
