name: Code Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - devel
      - pure-py
    paths:
      - "ktoolbox/**"
      - "tests/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "prod.env"
  pull_request:
    paths:
      - "ktoolbox/**"
      - "tests/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "prod.env"

jobs:
  test:
    name: Test Coverage
    runs-on: ${{ matrix.os }}
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    env:
      PYTEST_REPORT_FILENAME: report-${{ matrix.os }}-${{ matrix.python-version }}.html

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Pytest
        run: |
          poetry run pytest -v --capture=sys --cov --cov-report=xml tests/

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./tests/coverage.xml
          flags: ${{ github.ref_name }}
