name: Code Coverage

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - devel
      - pure-py
    paths:
      - "ktoolbox/**"
      - "tests/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "prod.env"
  pull_request:
    paths:
      - "ktoolbox/**"
      - "tests/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/codecov.yml"
      - "pyproject.toml"
      - "prod.env"

jobs:
  test:
    name: Test With Coverage
    runs-on: ${{ matrix.os }}
    concurrency:
      group: test-coverage-${{ github.ref }}-${{ matrix.os }}-${{ matrix.python-version }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        # macos-14 aka. macos-latest has switched to being an ARM runner, only supporting newer versions of Python.
        # https://github.com/actions/setup-python/issues/855#issuecomment-2096792205
        os: [ ubuntu-latest, windows-latest, macos-13 ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]
    env:
      PYTEST_REPORT_FILENAME: report-${{ matrix.os }}-${{ matrix.python-version }}.html

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Pytest
        run: |
          poetry run pytest -v --capture=sys --cov --cov-report=xml tests/

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: coverage.xml
          flags: ${{ matrix.os }}-${{ matrix.python-version }}
