name: Documentation
on:
  push:
    branches:
      - master
    paths:
      - "ktoolbox/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/docs.yml"
      - "pyproject.toml"
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Build and deploy to gh-pages branch
        run: |
          poetry run mike deploy --push --update-aliases master latest

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: site
