name: Documentation
on:
  push:
    branches:
      - master
    paths:
      - "ktoolbox/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/docs.yml"
      - "pyproject.toml"
      - "docs/**"
      - "mkdocs.yml"

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Build documentation
        run: |
          poetry run mkdocs build --clean --verbose
          poetry run mkdocs --version

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
