name: Documentation
on:
  push:
    branches:
      - master
    paths:
      - "ktoolbox/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/docs.yml"
      - "pyproject.toml"
      - "docs/**"
      - "mkdocs.yml"
  workflow_dispatch:

permissions:
  contents: write
#  id-token: write
#  pages: write

jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Build and push
        run: |
          git pull
          poetry run mike deploy --push --update-aliases master latest

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  documentation-pdf:
    name: Build documentation with PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python

      - name: Generate documentation PDFs
        env:
          ENABLE_PDF_EXPORT: 1
        run: |
          poetry run mkdocs build --clean

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ktoolbox-documentation-pdf
          path: |
            site/pdf/KToolBox-documentation.pdf
            site/zh/pdf/KToolBox-documentation.pdf
          retention-days: 30

# GitHub Pages will deploy from gh-pages branch automatically

#      - name: Deploy to GitHub Pages
#        uses: actions/deploy-pages@v2
