name: Publish Python Package

on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: "3.11"

      - name: Build package with Poetry
        run: poetry build

      - name: Publish package with Poetry
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish
