name: Publish Python Package

on:
  workflow_dispatch:
  push:

jobs:
  build:
    uses: ./.github/workflows/python-package.yml

  release:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v4

      - name: Download executable
        uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: Compress Directories
        run: |
          cd artifact
          for dir in */; do
            dir_name=$(basename "$dir")
            zip_file_name="${dir_name}.zip"
            zip -r "${zip_file_name}" "${dir}"
          done
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: artifact/*.zip
